In [6]:
## Poser des pixels de façcon optimal.

In [154]:
import numpy as np
import random
from PIL import Image as im
from matplotlib import pyplot as plt

In [155]:
#Paramètres:

correct_chance = 0 #chance de placer un bon pixel.
cooldown = 0 #Temps entre chaque pixel.
taille = 0 #Taille d'un groupe.
cote_canvas = 3 #Taille du coté du canvas

In [156]:
canvas = np.zeros((cote_canvas, cote_canvas, 3), dtype=np.uint8)

In [169]:
def plot_show(canvas):
    image = np.zeros((cote_canvas, cote_canvas, 3), dtype=np.uint8)
    color = {0: [255, 255, 255], 1: [255, 0, 0], 2: [0, 255, 0]}
    image[canvas == 0] = color[0]
    image[canvas == 1] = color[1]
    image[canvas == 2] = color[2]
    img = im.fromarray(image)
    img.save('output.png')
    img.show()

In [170]:
def agent(canvas, cote_canvas):
    x = int(random.random()*cote_canvas)
    y = int(random.random()*cote_canvas)
    canvas[x][y] = 1

In [171]:
canvas_test = np.zeros((cote_canvas, cote_canvas), dtype=np.uint8)
agent(canvas_test, 3)
print(canvas_test)

[[1 0 0]
 [0 0 0]
 [0 0 0]]


In [172]:
plot_show(canvas_test)